EnableImagePreviewing: true # default. Enables Image preview in your Terminal emulator (Kitty,Ghostty,Konosole,Wezterm)

InlineImagePreview: true

OutputFolder: "Pictures/Wallpaper/Catppuccin"

# ColorCorrectionBackend : nn
themes:
- name: "mocha"
  colors:
  # Core Base Colors
  - "#1e1e2e" # base       - Main background
  - "#181825" # crust      - Deepest dark (for shadows)
  - "#313244" # mantle     - Lighter background blocks (useful for contrast)
  - "#45475a" # surface0   - UI containers
  - "#585b70" # surface1   - Bordered UI blocks
  - "#6c7086" # surface2   - Dimmed text/background separators

  # Text & Subtext
  - "#cdd6f4" # text       - Primary readable foreground
  - "#bac2de" # subtext1   - Secondary text
  - "#a6adc8" # subtext0   - Dimmed subtext (labels, timestamps)

  # Accent Colors
  - "#f58da0" # red        - slightly brighter than #f38ba8
  - "#ed9db0" # pink       - soft & warm, better on dark backgrounds
  - "#fcc091" # peach      - boosted warmth, not oversaturated
  - "#fae6b9" # yellow     - gently lifted brightness
  - "#b0e8ae" # green      - fresher, cleaner tone
  - "#a2e7df" # teal       - more shine, preserves calmness
  - "#9be2f0" # sky        - just enough pop for UI elements
  - "#84d3f5" # sapphire   - richer blue with clarity
  - "#94c0ff" # blue       - closer to sky-blue for visibility
  - "#c4caff" # lavender   - ethereal highlight
  - "#d1afff" # mauve      - your main accent, softly intensified

  # Additional Utility
  - "#f5e0dc" # rosewater  - Subtle background/accent
  - "#11111b" # shadow     - Extreme dark (deeper than crust)
